/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GuidesGoogleScholarAlternativesRouteImport } from './routes/guides/google-scholar-alternatives'
import { Route as GuidesTrackingNewResearchRouteImport } from './routes/guides/tracking-new-research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGoogleScholarAlternativesRoute =
  GuidesGoogleScholarAlternativesRouteImport.update({
    id: '/guides/google-scholar-alternatives',
    path: '/guides/google-scholar-alternatives',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesTrackingNewResearchRoute =
  GuidesTrackingNewResearchRouteImport.update({
    id: '/guides/tracking-new-research',
    path: '/guides/tracking-new-research',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/google-scholar-alternatives': typeof GuidesGoogleScholarAlternativesRoute
  '/guides/tracking-new-research': typeof GuidesTrackingNewResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/google-scholar-alternatives': typeof GuidesGoogleScholarAlternativesRoute
  '/guides/tracking-new-research': typeof GuidesTrackingNewResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/google-scholar-alternatives': typeof GuidesGoogleScholarAlternativesRoute
  '/guides/tracking-new-research': typeof GuidesTrackingNewResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/profile'
    | '/sitemap.xml'
    | '/guides/google-scholar-alternatives'
    | '/guides/tracking-new-research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/profile'
    | '/sitemap.xml'
    | '/guides/google-scholar-alternatives'
    | '/guides/tracking-new-research'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookmarks'
    | '/profile'
    | '/sitemap.xml'
    | '/guides/google-scholar-alternatives'
    | '/guides/tracking-new-research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuidesGoogleScholarAlternativesRoute: typeof GuidesGoogleScholarAlternativesRoute
  GuidesTrackingNewResearchRoute: typeof GuidesTrackingNewResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/google-scholar-alternatives': {
      id: '/guides/google-scholar-alternatives'
      path: '/guides/google-scholar-alternatives'
      fullPath: '/guides/google-scholar-alternatives'
      preLoaderRoute: typeof GuidesGoogleScholarAlternativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/tracking-new-research': {
      id: '/guides/tracking-new-research'
      path: '/guides/tracking-new-research'
      fullPath: '/guides/tracking-new-research'
      preLoaderRoute: typeof GuidesTrackingNewResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuidesGoogleScholarAlternativesRoute: GuidesGoogleScholarAlternativesRoute,
  GuidesTrackingNewResearchRoute: GuidesTrackingNewResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
